### PR TITLE
XDR-2451: Add Azure role assignment module

### PR DESCRIPTION
**Pull request by deepanshumarwah**

### CODE REVIEW

**Review by GerardSetho — DISMISSED** [review]
Looks good

**Review by chrisjaimon2012 — CHANGES_REQUESTED** [review]
We can make the below suggested changes to make the package more generic for future use

**Review by chrisjaimon2012 — CHANGES_REQUESTED** [review]
One more minor thing, rest LGTM

**Review by chrisjaimon2012 — APPROVED** [review]
:shipit:

**Pull request merged**
